baseURL = "https://avisord.github.io/journal/"
languageCode = "en-us"
title = "Avinash's Engineering Journal"

[params]
  description = "Problems encountered. Decisions made. Commands explained."

[markup]
  [markup.highlight]
    style = "native"
    lineNos = false
    codeFences = true
    guessSyntax = true
    noClasses = true
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
